server:
  port: 8888

spring:
  config.name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/the5tranger/capstone-configurations
          clone-on-start: true

